#################################
## Vitulus device icon status message
#################################

Header  header
string  supply      # ONLINE, FAIL, OFFLINE, DISABLED
string  batt        # FULL, 75, 50, 25, EMPTY, DISABLED
string  fan_int     # ON, OFF, DISABLED
string  temp_int    # OK, WARM, HOT, DISABLED
string  fan_ext     # ON, OFF, DISABLED
string  temp_ext    # OK, WARM, HOT, DISABLED
string  mot_lf      # OK, WARM, HOT, DISABLED
string  mot_rf      # OK, WARM, HOT, DISABLED
string  mot_lr      # OK, WARM, HOT, DISABLED
string  mot_rr      # OK, WARM, HOT, DISABLED
string  mower       # ON, BUSY, ERROR, DISABLED
string  imu         # ON, OFF, DISABLED
string  gnss_nav    # RTK, 3DFIX, BAD, DISABLED
string  gnss        # RTK, 3DFIX, BAD, DISABLED
string  wifi        # FINE, MEDIUM, BAD, DISCONNECTED
string  lidar       # ON, OFF, DISABLED
string  d435        # ON, OFF, DISABLED
string  t265        # ON, OFF, DISABLED
